### ISSUE TITLE
Confusion matrix in mnist example fails to update with cortex 0.9

### ISSUE THREAD

**Issue by cnuernber** [thinktopic/cortex#102]
Running the mnist example will fail to update the confusion matrix on the client (browser).  I believe this works with 0.5.0 but I haven't specifically tracked it down.

**Comment by harold** [comment]
It's worse than that. The example needs to be updated for the dataset changes, etc... I'll look at it.

**Comment by harold** [comment]
PR: https://github.com/thinktopic/cortex/pull/141
