### ISSUE TITLE
cortex/local-install.sh is not in the repo

### ISSUE THREAD

**Issue by shaaza** [thinktopic/cortex#114]
The readme says `make sure to run cortex/local-install.sh before running an example`, but that script doesn't exist in the repo. 

Has this script been replaced by just `lein install`? If yes, we could update the readme. If not, we could dig it up from an older commit.

**Comment by harold** [comment]
https://github.com/thinktopic/cortex/commit/4e98dad69b14d67dbb5e885c321a95cc76cea69e
