### ISSUE TITLE
local-install.sh file not found

### ISSUE THREAD

**Issue by Aljendro** [thinktopic/cortex#137]
The README has a reference to run local-install.sh, but the file was deleted a while ago...
I am not sure how to replicate the file so that it works with the current state of the project.

**Comment by harold** [comment]
Thanks for this report! Cortex has been simplified significantly recently, obviating the need for the `local-install.sh` script.

Now, if you want to run from the latest, a simple `lein install` of the projects you plan to build/develop/run locally will do.

Personally, I run something like this pretty frequently:
```
harold@gibson:~/src$ cd cortex/
harold@gibson:~/src/cortex$ lein install
Compiling 1 source files to /home/harold/src/cortex/target/classes
Created /home/harold/src/cortex/target/cortex-0.9.3-SNAPSHOT.jar
Wrote /home/harold/src/cortex/pom.xml
Installed jar and pom into local repo.
harold@gibson:~/src/cortex$ cd experiment/
harold@gibson:~/src/cortex/experiment$ lein install
Created /home/harold/src/cortex/experiment/target/experiment-0.9.3-SNAPSHOT.jar
Wrote /home/harold/src/cortex/experiment/pom.xml
Installed jar and pom into local repo.
```

I'll also look at updating the readme. Thanks again.

**Comment by harold** [comment]
Here is what that file looked like (in case that's helpful for some reason):
https://github.com/thinktopic/cortex/blob/cb75dd243f3229997846df64fbbb9c6007f7a386/local-install.sh
