### ISSUE TITLE
Is `experiment` too general of a name?

### ISSUE THREAD

**Issue by harold** [thinktopic/cortex#145]
Maybe cortex-experiment is a better name?

https://github.com/thinktopic/cortex/pull/141/files/242793ae249606c2f708e20baff15e607b273934#diff-e5046d343c37d85d4d736af438324a36R2

**Comment by charlesg3** [comment]
This doesn't seem high-priority enough to keep as an issue. It isn't really affecting anything at this point so I'm closing this until it becomes an actual "issue"
