### ISSUE TITLE
Is there any documentation available for Cortex?

### ISSUE THREAD

**Issue by xukai92** [thinktopic/cortex#164]

**Comment by harold** [comment]
Currently there are three main sources of information.

1. Markdown files in this repo.
2. Tests in projects in this repo.
3. Docstrings on relevant sources.

We intend, for version 1.0 (https://github.com/thinktopic/cortex/issues/154), to unify, correct, and expand these into proper docs.

In the mean time, feel free to ask any questions you have either here (as you already have), or on the [mailing list](https://groups.google.com/forum/#!forum/clojure-cortex).

Hope that helps. Take care.
