### ISSUE TITLE
Document GPU setup for Cortex for multiple environments

### ISSUE THREAD

**Issue by benkamphaus** [thinktopic/cortex#24]
I believe we've tested Cortex setup on Ubuntu 14.04, 16.04, and 16.10. It would be nice to get input and documentation on configuration steps. In addition, I believe @rosejn has gotten Cortex working on an older Nvidia Mac, relevant to [an issue raised](https://groups.google.com/forum/#!topic/clojure-cortex/JiKAG4-GVLQ) by @gigasquid on the mailing list.

The older `cortex-gpu` project used to contain detailed instruction steps for getting Cortex configured to run on the GPU. The reason this went away is, fortunately, that the setup has been _greatly_ simplified compared to where it was. Even though instructions are simpler now, it would be nice to have these steps documented. I know @charlesg3 has recently setup both an AWS configuration and a local 16.10 ubuntu desktop.

If anyone wants to point me at resources anyone's used or document steps they've taken here, I can also just take a stab at consolidating everything.

**Comment by charlesg3** [comment]
Definitely willing to help this effort. 

Basic steps include, at minimum: Installing nvidia-cuda-toolkit (`sudo apt-get install nvidia-cuda-toolkit`)
and installing cudnn available from here: https://developer.nvidia.com/cudnn publicly. 

The .zip contains some libraries that you will need to make available to the loader. I simply copied the library files to `/usr/lib`, though I'm sure there's a better way of doing this.

Depending on which distribution you're on you will either have cuda7.5 or cuda8.0. Current master is 7.5, if you're running 8.0 you will need to use the following branch (basically specifies a different dep for the jni bindings -- o/w code is identical): 

https://github.com/thinktopic/cortex/tree/cuda-8.0

There's a couple of other deps that need to be installed which are available for ubuntu, I'd have to start fresh to remember.

**Comment by gigasquid** [comment]
@charlesg3 Thanks for the help. My problem was that I had cuda 8.0 and needed the different dep.

My install steps on Mac OSX were:

 Followed the instructions for gpu setup from [Tensor Flow](https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#optional-setup-gpu-for-mac)
Brew install coreutils and CUDA toolkit 
 * `$ brew install coreutils`
 * ` $ brew tap caskroom/cask`
 * `$ brew cask install cuda`

Add CUDA Tool kit to bash profile

```
export CUDA_HOME=/usr/local/cuda
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$CUDA_HOME/lib"
export PATH="$CUDA_HOME/bin:$PATH"
```

Download the CUDA Deep Neural Network [libraries](https://developer.nvidia.com/cudnn) 

Once downloaded and unzipping, moving the files:
```
$ sudo mv include/cudnn.h /Developer/NVIDIA/CUDA-8.0/include/
$ sudo mv lib/libcudnn* /Developer/NVIDIA/CUDA-8.0/lib
$ sudo ln -s /Developer/NVIDIA/CUDA-8.0/lib/libcudnn* /usr/local/cuda/lib/
```

Finally, as stated above, using the `cuda-8.0` branch and running the tests and being amazed at how fast they are. 🐎

**Comment by charlesg3** [comment]
@gigasquid -- much thanks for including the steps you took to get it working.

For posterity I've updated the README.md with each of our comments for now. We'll expand the setup instructions shortly.

**Comment by wanghaisheng** [comment]
mac 10.12.1 follow setup instruction in README does not work
```
➜  cuda cd /usr/local/cuda/samples
➜  samples ls
0_Simple        3_Imaging       6_Advanced      Makefile
1_Utilities     4_Finance       7_CUDALibraries common
2_Graphics      5_Simulations   EULA.txt
➜  samples sudo make -C 1_Utilities/deviceQuery
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
expr: syntax error
/Developer/NVIDIA/CUDA-8.0/bin/nvcc -ccbin g++ -I../../common/inc  -m64  -Xcompiler -arch -Xcompiler x86_64  -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_60,code=compute_60 -o deviceQuery.o -c deviceQuery.cpp
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/Developer/NVIDIA/CUDA-8.0/bin/nvcc -ccbin g++   -m64  -Xcompiler -arch -Xcompiler x86_64  -Xlinker -rpath -Xlinker /Developer/NVIDIA/CUDA-8.0/lib  -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_60,code=compute_60 -o deviceQuery deviceQuery.o 
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
mkdir -p ../../bin/x86_64/darwin/release
cp deviceQuery ../../bin/x86_64/darwin/release
➜  samples ./bin/x86_64/darwin/release/deviceQuery
./bin/x86_64/darwin/release/deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 35
-> CUDA driver version is insufficient for CUDA runtime version
Result = FAIL
```

**Comment by wanghaisheng** [comment]
```
➜  cuda sudo mv include/cudnn.h /Developer/NVIDIA/CUDA-8.0/include/
➜  cuda sudo mv lib/libcudnn* /Developer/NVIDIA/CUDA-8.0/lib       
➜  cuda cd /usr/local/cuda/samples
➜  samples sudo make -C 1_Utilities/deviceQuery                  
make: Nothing to be done for `all'.
➜  samples ./bin/x86_64/darwin/release/deviceQuery                  
./bin/x86_64/darwin/release/deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 35
-> CUDA driver version is insufficient for CUDA runtime version
Result = FAIL
```

**Comment by rogerallen** [comment]
@wanghaisheng if you are still having issues, I believe you'll want to visit http://www.nvidia.com/object/mac-driver-archive.html and get an up-to-date CUDA driver for the Mac.

**Comment by wanghaisheng** [comment]
@rogerallen  thx very much i will try

**Comment by cjwallace** [comment]
Since @gigasquid's installation instructions (thanks!) for OSX, `cuda` has moved from `caskroom/cask` to `caskroom/drivers` in brew, so I think the updated instructions should be:

- `$ brew install coreutils`
- `$ brew tap caskroom/drivers`
- `$ brew cask install cuda`

Brew will tell anyone who tries `caskroom/cask` this in any case.

**Comment by charlesg3** [comment]
@cjwallace -- thanks much for this info. I've just updated the install instructions, though I don't have a machine with OSX on it to test. Let me know if there's anything else that needs to be updated to get things working in that flow.

Cheers!

**Comment by cnuernber** [comment]
I feel this is at this point good enough.  If anyone feels strongly otherwise, let's discuss it and I will possibly reopen.
