### ISSUE TITLE
Cask 'cuda' is unavailable

### ISSUE THREAD

**Issue by gzmask** [thinktopic/cortex#252]
Probably just a minor README update thing:

brew cask install cuda
Error: Cask 'cuda' is unavailable: No Cask with this name exists. Did you mean one of these?
cuda-z                                   nvidia-cuda

**Comment by harold** [comment]
Hi! Thanks for this.

We don't have any active Mac users in the office at the moment.

I'm happy to include anything that helps you in the README, if there are a set of helpful steps we'd love a PR or any information that may be useful to future Max cortex users.

**Comment by iboss-ptk** [comment]
cuda in caskroom/driver has already [renamed to nvidia-cuda since Oct 22](https://github.com/caskroom/homebrew-drivers/commit/f56e9ab9b8e2865e7c5965d014bcaa06ed196f19#diff-f9032f896f3316d57d071c60b61fa9c6)

**Comment by harold** [comment]
Neat, thanks!
