### ISSUE TITLE
Fix license/copyright on cortex/dataset and examples/dropout

### ISSUE THREAD

**Issue by ricardojmendez** [thinktopic/cortex#4]
Subprojects `cortex/dataset` and `examples/dropout` still have the standard boilerplate for the license, with 

    Copyright © 2016 FIXME

This applies to both the README and the `project.clj` files.  While the license on the project files is stated as Eclipse, it'd likely look more official if the copyright wasn't the default.

**Comment by charlesg3** [comment]
@ricardojmendez -- Thanks for the feedback. I have updated the license information. Please feel free to let us know if there's anything else that has been omitted. Closing this issue for now.
