### ISSUE TITLE
Resetting loss "high score"?

### ISSUE THREAD

**Issue by bburdette** [thinktopic/cortex#80]
I'm training a net now and it has a certain loss score which is saved with the net.  This loss score is from a randomly generated holdout dataset.  

When I start a new training session, presumably a new holdout dataset is created, perhaps giving a higher base error score.  Even though the net improves its score with the new holdout, the improved net is never saved since the score may never reach that of the old holdout dataset.  

It might be a good idea to generate a new high score when there is a new holdout dataset, or have a way to explicitly reset the high score.

**Comment by cnuernber** [comment]
I am not certain that I think changing the holdout set ever is a good idea.  How do you ensure that over time your net doesn't see all of the data during training?

**Comment by bburdette** [comment]
In my case I believe the holdout dataset is generated randomly - I'm assuming if you exit the repl and come back later, you get a new holdout dataset.  Unless the holdout is saved with the network?

**Comment by cnuernber** [comment]
OK, so for entirely generated datasets then if you just:
```clojure
(dissoc network :cv-loss)
```

You would effectively reset the loss thus forcing the system to save the network.

**Comment by bburdette** [comment]
Ok I'll give that a try!

**Comment by bburdette** [comment]
added a flag to train-n, in branch "reset-score"

**Comment by harold** [comment]
Link: https://github.com/thinktopic/cortex/compare/reset-score

**Comment by cnuernber** [comment]
https://github.com/thinktopic/cortex/pull/81
