### ISSUE TITLE
Make file fails on fresh install and MNIST run

### ISSUE THREAD

**Issue by ghostandthemachine** [thinktopic/cortex#85]
When running `train.sh` in in the suite-classification project I get this:

```
suite-classification[master] % ./train.sh
rm resources/public/css/app.css
rm: resources/public/css/app.css: No such file or directory
make: *** [resources/public/css/app.css] Error 1
Error: Unable to access jarfile target/classify-example.jar
```

**Comment by cnuernber** [comment]
We will grown the number of examples over time and solving this issue for all of them is a requirement as well as addressing a few other things.  I believe this is a must for a 1.0 release.

**Comment by gigasquid** [comment]
I think this can be closed 😸

**Comment by cnuernber** [comment]
Good point :-).
