### ISSUE TITLE
UnsatisfiedLinkError: no hdf5_cpp in java.library.path

### ISSUE THREAD

**Issue by JulioBarros** [thinktopic/cortex#88]
I'm getting this error and UnsatisfiedLinkError: no jnihdf5, no jnicuda when trying to use Cortex. I'm on a mac with cudann 8.0 installed.

I see the comment in the Read be but believe cudann is installed correctly as it works fine with Keras/Theano/TensorFlow.  

I see in https://github.com/thinktopic/cortex/issues/24 there is a mention of another branch with a different dependency but that branch does not seem to be available any longer.

Is there anything I can do to see if my installation is in fact correct? What was the difference in that "cuda-8.0" branch?

Thanks.

Julio

**Comment by cnuernber** [comment]
OK this needs to be documented but I see it is not:

First, to get the gpu unit tests to work for gpu-compute you need to uncomment this line:
https://github.com/thinktopic/cortex/blob/master/gpu-compute/project.clj#L9

Then if they don't work there is probably an issue with cudnn.  

The hdf5 stuff won't work but that isn't required for using cortex in general; it is only required for importing models from caffe.  Once the model is in nippy format it isn't required any more.

Then there is a similar change you would need to make in examples/suite-classification/project.clj; basically the javacpp-cuda-8 libraries need to be used.

**Comment by cnuernber** [comment]
Closing this for now.  We could definitely use better docs around here but Julio has a working system at this point.
