### ISSUE TITLE
suite/train - more per-epoch functional user overrides

### ISSUE THREAD

**Issue by harold** [thinktopic/cortex#90]
https://github.com/thinktopic/cortex/blob/f6951075a83076bec11e6520202e913c0541423a/suite/src/cortex/suite/train.clj#L176

In talking with @charlesg3 there may be an opportunity here for `take-while` and a user-provided function that could run extra tests, do `think.peer` things or re-implement the old `train-until-error-stabilizes`. Interested to hear other's thoughts here.

**Comment by cnuernber** [comment]
I would really like help with this portion of cortex.  I built it out a ways to make doing things easy but it is opinionated and I don't think it is particularly well designed.

**Comment by poojaramesh** [comment]
@harold: To add to your point about running extra tests, it would be very helpful to be able to choose what gets printed out during training (https://github.com/thinktopic/cortex/blob/master/suite/src/cortex/suite/train.clj#L50). For example, with the multilabel classification problem (multi-channel approach), the usual cross entropy loss print out is useful to monitor the training, but being able to call a user-defined function that calculates the hamming loss for each epoch, and printing that out might be more interpretable.

**Comment by harold** [comment]
@poojaramesh - yup! This exactly parallels some of the other tests (intersection over union for bbox stuff, etc..) that we've wanted. Thanks for writing it out so clearly.

My other change from this morning paves the way for this a bit, making it possible to simplify what's printed, so when other things are printed they are easier to see:
https://github.com/thinktopic/cortex/pull/91

I think we're definitely headed in the right direction here.

**Comment by harold** [comment]
I am happy with the state of this now.

`experiment/train-n` now takes a `test-fn`:
https://github.com/thinktopic/cortex/blob/master/experiment/src/cortex/experiment/train.clj#L191

This can be used to implement arbitrary metric calculations per-epoch:
https://github.com/thinktopic/cortex/blob/242793ae249606c2f708e20baff15e607b273934/experiment/src/cortex/experiment/classification.clj#L168

That example calculates classification accuracy per-epoch both to decide if a newly trained net is the best yet, and for real-time display during training.
