### ISSUE TITLE
Clojure 1.9 support?

### ISSUE THREAD

**Issue by cnuernber** [thinktopic/cortex#95]
Cortex deals with a lot of complex datastructures that we could use some help with.  I would like to start a discussion on some reasonable strategy to make these datastructures a bit less opaque which means at the very least an informal schema with some definitions.  If we go there then why not use spec and think through the datastructures and their implications a bit?  

This is marked for 1.0 because this process will help greatly with the longevity of the software.

**Comment by gigasquid** [comment]
IMO Spec could be useful in a number of places:

- Validating input to functions and better error messages.
- Once things are speced like network/layers, the `conform` could be useful for destructing things in other places.
- It could be useful in "surprising" ways. For example, the generative nature of specs could enable exploration with generated network architectures and Genetic Algos.

**Comment by bburdette** [comment]
Just a quick note:  I'm using cortex in a project that has clojure at 1.9.0-alpha17.  I encountered some strange spec errors which appeared when I tried requiring cortex.nn.execute, but occurred in core.async someplace.  These were fixed by adding an updated version of core.async, namely  [org.clojure/core.async "0.3.443"]

Also perhaps useful: adding that same core.async dependency to cortex allows it to pass its tests using 1.9.0-alpha17.

**Comment by gigasquid** [comment]
I have a branch with 1.9 changes and everything that I could test, (everything but the importers), seems to work. I did require a tweak in think.image from a clojure.spec error but other than that there were no real surprises. 

I can create a pull request for both cortex and think.image changes if you are interested.

**Comment by cnuernber** [comment]
Yes, absolutely we would be interested.

**Comment by gigasquid** [comment]
Cool - here are the branches https://github.com/thinktopic/cortex/pull/190, https://github.com/thinktopic/think.image/pull/10. Definitely would benefit from additional pairs of eyes, testing.

**Comment by harold** [comment]
Hi @gigasquid, thanks for this. @cnuernber is out this week, so don't panic if there isn't movement on this right away. We have internal projects that are moving to 1.9 so this is a priority for us as well. We appreciate your interest and effort as always.

**Comment by gigasquid** [comment]
This is done right? Can it be closed?

**Comment by cnuernber** [comment]
Yes, sorry, this is done.
